### ISSUE TITLE
Filter old basecalls in Albacore FAST5s

### ISSUE THREAD

**Issue by johnomics** [scottgigante/picopore#6]
Thanks for writing such a useful tool. I have some FAST5s with MinKNOW basecalls that have been recalled with Albacore. I'd like to remove the MinKNOW basecalls from these files and then compress the Albacore calls with picopore. It looks like picopore could remove the MinKNOW basecalls with `-manual`, but this only works in raw mode, and I don't want to use this because the Albacore basecalls would be lost. Is it possible to make `-manual` work in lossless and deep-lossless modes? Or perhaps add an option to retain only the most recent basecall group?

**Comment by scottgigante** [comment]
Hi John,

Thanks for your message!

I'm not sure that using `--manual` on lossless or deep-lossless makes a lot of sense. Lossless compression leaves the entire file structure the same as pre-compression, so if you're spending the time to run picopore you may as well compress the whole thing (it has minimal if any impact on downstream analysis runtime.) Deep-lossless, on the other hand, totally changes the structure of the file, and leaving parts of it intact while restructuring others will likely cause unintended problems with third-party tools. 

This doesn't mean I can't solve your problem. To clarify, are you intending on retaining the event data? If you're not, and you simply want to retain albacore's FASTQ and summary data while deleting MinKNOW's, you could run `--mode raw --fastq --summary --manual <minKNOW_group_name>`. If you do intend on retaining the event data, here's a proposition. I have been thinking about reworking the `--manual` option to allow full reign over how `--mode raw` currently functions. 

Essentially at the moment `--mode raw` removes datasets and groups matching the following keywords:
`["Alignment","Log","Configuration","HairpinAlign","Calibration_Strand","Hairpin_Split","EventDetection","Events","Segmentation"]`
and depending on the combination of selections from `--summary, --no-summary, --fastq, --no-fastq`, adds some / none / all of the following:
`["Summary","BaseCalled","Basecall"]`

Currently, `--manual` just adds to this list. If I see a use case (yours may be one) I'm willing to open up manual to a bit more freedom, replacing the list rather than adding to it. That way, you will *only* remove the datasets you specify. Will this solve your problem?

Cheers,
Scott

**Comment by johnomics** [comment]
Hi Scott - thanks for the detailed reply, sorry it's taken me a few days to get back to you.

I want to keep the Albacore events (and everything else about the Albacore calls, as well as compressing them), but delete the MinKNOW events. I was thinking about deleting everything about the MinKNOW calls, but maybe it would be useful for some users to retain the MinKNOW FASTQs and summary.

So yes, more granular options for `--manual` should do the trick (i.e. target <minKNOW_group_name> "Events" or something).

This particular use case might be quite limited; we only want to use it for older flow cells where we generated MinKNOW calls and are now re-calling with Albacore. Although Albacore creates new FAST5s, there is no option to remove old basecalls first, so we are ending up with two sets of events in these files, taking up a lot of space, without a simple way to clean up the old set.

However, our new MinION runs are only getting called with Albacore, so the problem doesn't arise - at the moment. But there are likely to be significant upgrades to Albacore, and other base callers, so the problem may reoccur.

**Comment by scottgigante** [comment]
No worries John. I've changed around `--manual` mode a little - I think I like it better this way anyway. Now manual *only* removes groups that match your specification (overriding default raw behaviour) and also accepts regular expressions. So to solve your issue, you would run

```
picopore -y --mode raw --manual <MinKNOW_group>/Events /path/to/files
picopore -y --mode lossless /path/to/files
```

Maybe try it with `--prefix` first to be sure that you're getting what you want. I see this being fairly common (I'm re-basecalling an old dataset as we speak) so if you're happy with it, please close this issue and I'll push the changes to pypi.

**Comment by johnomics** [comment]
Hi Scott, thank you very much for getting to this so quickly. Unfortunately it doesn't seem to be working quite as we might expect. I removed my existing picopore installation, cloned the new version and compiled it. I've tested it on a single MinKNOW called read:

```
$ ls -l minknow_read
total 168
-rwxr-x--x 1 john john 171873 May 22 12:06 test.fast5

$ h5dump minknow_read/test.fast5 | grep -e GROUP -e DATASET
GROUP "/" {
   GROUP "Analyses" {
      GROUP "Basecall_1D_000" {
         GROUP "BaseCalled_template" {
            DATASET "Events" {
            DATASET "Fastq" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Segmentation_000" {
         GROUP "Summary" {
            GROUP "segmentation" {
   GROUP "Raw" {
      GROUP "Reads" {
         GROUP "Read_83" {
            DATASET "Signal" {
   GROUP "UniqueGlobalKey" {
      GROUP "channel_id" {
      GROUP "context_tags" {
      GROUP "tracking_id" {
```

Run Albacore on this read:
```
$ read_fast5_basecaller.py -f FLO-MIN106 -k SQK-LSK108 -s picopore_manual_albacore -i minknow_read -o fast5 -t 1
```

Clean up the Albacore output folder so it just contained the output read:
```
$ ls -l picopore_manual_albacore/
total 480
-rw-r--r-- 1 john john 488127 May 22 12:09 test.fast5

$ h5dump picopore_manual_albacore/test.fast5 | grep -e GROUP -e DATASET
GROUP "/" {
   GROUP "Analyses" {
      GROUP "Basecall_1D_000" {
         GROUP "BaseCalled_template" {
            DATASET "Events" {
            DATASET "Fastq" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Basecall_1D_001" {
         GROUP "BaseCalled_template" {
            DATASET "Events" {
            DATASET "Fastq" {
         GROUP "Configuration" {
            GROUP "basecall_1d" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Segmentation_000" {
         GROUP "Summary" {
            GROUP "segmentation" {
      GROUP "Segmentation_001" {
         GROUP "Configuration" {
            GROUP "event_detection" {
            GROUP "stall_removal" {
         GROUP "Summary" {
            GROUP "segmentation" {
   GROUP "Raw" {
      GROUP "Reads" {
         GROUP "Read_83" {
            DATASET "Signal" {
   GROUP "UniqueGlobalKey" {
      GROUP "channel_id" {
      GROUP "context_tags" {
      GROUP "tracking_id" {
```

Copy to two test folders:
```
$ mkdir picopore_manual_raw_events picopore_manual_raw_000
$ cp picopore_manual_albacore/test.fast5 picopore_manual_raw_events
$ cp picopore_manual_albacore/test.fast5 picopore_manual_raw_000
```

Removing `Basecall_1D_000` completely works, but it appears to do lossless compression as well - doing lossless compression on this read afterwards has no effect (in fact it increases the file size slightly):
```
$ picopore -y --mode raw --manual Basecall_1D_000 picopore_manual_raw_000
Performing raw compression with manual keyword Basecall_1D_000 on 1 files...
Complete.
Original size:   488127
Compressed size: 265790

$ h5dump picopore_manual_raw_000/test.fast5 | grep -e GROUP -e DATASET
GROUP "/" {
   GROUP "Analyses" {
      GROUP "Basecall_1D_001" {
         GROUP "BaseCalled_template" {
            DATASET "Events" {
            DATASET "Fastq" {
         GROUP "Configuration" {
            GROUP "basecall_1d" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Segmentation_000" {
         GROUP "Summary" {
            GROUP "segmentation" {
      GROUP "Segmentation_001" {
         GROUP "Configuration" {
            GROUP "event_detection" {
            GROUP "stall_removal" {
         GROUP "Summary" {
            GROUP "segmentation" {
   GROUP "Raw" {
      GROUP "Reads" {
         GROUP "Read_83" {
            DATASET "Signal" {
   GROUP "UniqueGlobalKey" {
      GROUP "channel_id" {
      GROUP "context_tags" {
      GROUP "tracking_id" {

$ picopore -y --mode lossless picopore_manual_raw_000
Performing lossless compression on 1 files...
Complete.
Original size:   265790
Compressed size: 268852
```

Removing the Events only works too, but also does lossless compression:
```
$ picopore -y --mode raw --manual Basecall_1D_000/BaseCalled_template/Events picopore_manual_raw_events
Performing raw compression with manual keyword Basecall_1D_000/BaseCalled_template/Events on 1 files...
Complete.
Original size:   488127
Compressed size: 273561

$ h5dump picopore_manual_raw_events/test.fast5 | grep -e GROUP -e DATASET
GROUP "/" {
   GROUP "Analyses" {
      GROUP "Basecall_1D_000" {
         GROUP "BaseCalled_template" {
            DATASET "Fastq" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Basecall_1D_001" {
         GROUP "BaseCalled_template" {
            DATASET "Events" {
            DATASET "Fastq" {
         GROUP "Configuration" {
            GROUP "basecall_1d" {
         GROUP "Summary" {
            GROUP "basecall_1d_template" {
      GROUP "Segmentation_000" {
         GROUP "Summary" {
            GROUP "segmentation" {
      GROUP "Segmentation_001" {
         GROUP "Configuration" {
            GROUP "event_detection" {
            GROUP "stall_removal" {
         GROUP "Summary" {
            GROUP "segmentation" {
   GROUP "Raw" {
      GROUP "Reads" {
         GROUP "Read_83" {
            DATASET "Signal" {
   GROUP "UniqueGlobalKey" {
      GROUP "channel_id" {
      GROUP "context_tags" {
      GROUP "tracking_id" {
```

Is this working as expected? Here is the read if you want to try to replicate this test: [test.fast5.zip](https://github.com/scottgigante/picopore/files/1018634/test.fast5.zip)

**Comment by scottgigante** [comment]
Hi John,

Thanks for the detailed logs. If we ignore the second step of lossless compression, this is working as expected - all Picopore modes repack the fast5 files with GZIP level 9 (Albacore defaults to level 1), so you expect a decent size reduction on the remaining data after raw compression. 

I'll look into why the lossless compression isn't improving on the Events dataset - it may be that ONT have improved their data typing since I wrote this algorithm. In the meantime, you can be confident that `--manual` is working as expected - it's just the lossless compression which isn't giving us any improvement.

Cheers,
Scott

**Comment by johnomics** [comment]
Ah, thanks, that makes sense. I forgot the raw mode did GZIP compression. I don't think lossless (or deep-lossless) is doing very much on Albacore basecalls - some of my other tests look like they had similar results. And it looks like maybe ONT are using level 9 compression across the board now - the signal data from more recent MinKNOW 1.5+ runs (later than the read above, which was from MinKNOW 1.3) are not reduced in size by picopore raw mode. Thanks for your help.

**Comment by scottgigante** [comment]
Thanks John. I haven't had a chance to play with the later versions of MinKNOW, but I'll have a look and see if I can squeeze out some further improvements.
